function fss = f_fun(t,in2)
%F_FUN
%    FSS = F_FUN(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    20-Aug-2022 12:45:12

Omega = in2(4,:);
Omegad = in2(2,:);
psid = in2(3,:);
psidd = in2(1,:);
psi = in2(5,:);
t2 = cos(psi);
t3 = sin(psi);
t4 = psid.*3.0;
t6 = sqrt(3.0);
t5 = t2.^2;
t7 = t2.*(9.0./2.0);
t8 = t4.*t6;
t9 = t2.*(3.0./2.56e+2);
t10 = t2.*t6.*(3.0./2.0);
t11 = (t2.*t6)./2.56e+2;
t12 = t7+t10+2.0;
t13 = t9+t11+1.0./1.92e+2;
fss = [Omegad.*t12.*(-1.0./3.84e+2)+Omegad.*t13-t3.*t6.*1.22625e-1-(Omega.*t3.*t6.*(Omega.*(3.0./2.0)+t4+t8+Omega.*t6.*(3.0./2.0)-Omega.*t2.*t6.*2.0))./7.68e+2+(Omega.*psid.*t3.*t6.*(t6+1.0))./2.56e+2;psidd.*t12.*(-1.0./3.84e+2)+psidd.*t13+Omegad.*(t5.*(-1.0./1.28e+2)+t6.*1.796875e-2+t9+t11+6.419270833333333e-2)-(Omegad.*(t2.*(9.0./4.0)-t5.*(3.0./2.0)+t6.*(6.9e+1./2.0e+1)+t2.*t6.*(3.0./4.0)+4.93e+2./4.0e+1))./1.92e+2+(psid.*t3.*t6.*(Omega.*3.0+t4+t8+Omega.*t6.*3.0-Omega.*t2.*t6.*4.0))./7.68e+2;psid;Omega];
