function Mss = M_fun(t,in2)
%M_fun
%    Mss = M_fun(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    20-Aug-2022 12:45:43

psi = in2(3,:);
t2 = cos(psi);
t3 = sqrt(3.0);
t4 = t2.*(3.0./2.56e+2);
t5 = (t2.*t3)./2.56e+2;
t6 = t4+t5+1.0./1.92e+2;
Mss = reshape([1.0./9.6e+1,t6,0.0,0.0,t6,t3.*1.796875e-2+t4+t5-t2.^2./1.28e+2+6.419270833333333e-2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
